GET https://localhost:5001/api/Parking/1

###

POST https://localhost:5001/api/Parking
content-type: application/json

{
    "PersonName": "Boba Fett",
    "StarShip": "Star Destroyer",
    "arrivalTime": "2021-04-29T13:37:00",
    "payed": false
}

###

PUT https://localhost:5001/api/Parking/1
content-type: application/json

{
    "id": 1,
    "PersonName": "Ja hej hej"
}