GET https://localhost:5001/api/Parking

###

POST https://localhost:5001/api/Parking/register
content-type: application/json

{
    "PersonName": "boba fett",
    "StarShip": "millennium falcon",
    "arrivalTime": "2021-03-29T13:37:00",
    "SpacePortID": 3
}

###

PUT https://localhost:5001/api/Parking/8
content-type: application/json

{
    "id": 8,
    "PersonName": "Ja hej hej"
}

###

POST https://localhost:5001/api/SpacePorts
content-type: application/json

    {
        "Name": "ESH spaceport",
        "TotalCapacity": 10
    }